
IF OBJECT_ID ('tempdb.dbo.#PRODUTIVIDADE') is not null 
DROP TABLE #PRODUTIVIDADE

SELECT 
A.REF,
C.DIRETORIA, 
C.UF,
C.PRODUTO,
B.DESC_EVENTO,
A.ID_NUM,
A.NOME,
A.SITUACAO,
D.CARGO_AGRUPADO,
CASE WHEN B.[D/C] = 'Crédito' then -[VALOR] ELSE [VALOR] END AS SALDO 
INTO #PRODUTIVIDADE
 FROM 
BDRH.FPW.CONTABILFOLHA A WITH (NOLOCK)
LEFT JOIN
BDRH.CUSTO.Tbl_Evento_Conta B WITH (NOLOCK)
ON
A.COD_EVENTO=B.EVENTO
LEFT JOIN
BDRH.CUSTO.TBL_CENTRO_CUSTO C WITH (NOLOCK)
ON
A.CENTRO_CUSTO_NUM=C.CENTRO_CUSTO_NUM
LEFT JOIN
BDRH.CUSTO.TBL_CARGO_AGRUPADO D WITH (NOLOCK)
ON
A.COD_CARGO=D.COD_CARGO
WHERE REF >= '202201'
AND CONTA_SEREDE = '31102004'

SELECT 
REF,
DIRETORIA, 
UF,
PRODUTO,
DESC_EVENTO,
ID_NUM,
NOME,
SITUACAO,
CARGO_AGRUPADO,
SUM (SALDO)
FROM 
#PRODUTIVIDADE
GROUP BY
REF,
DIRETORIA, 
UF,
PRODUTO,
DESC_EVENTO,
ID_NUM,
NOME,
SITUACAO,
CARGO_AGRUPADO

