
----TABELA FOPAG

IF OBJECT_ID ('tempdb.dbo.#TBL_FOPAG') is not null 
DROP TABLE #TBL_FOPAG

SELECT 
A.REEF,
B.MATRICULA,
A.CPF,
B.NOVA_DIRETORIA,
A.UF,
B.CC,
B.PRODUTO,
B.CARGO_AGRUPADO,
A.VALOR_FINAL,
B.MACRO_PRODUTO
INTO #TBL_FOPAG
FROM BDRV.DBO.FOPAG_SEREDE_CONECTA A
INNER JOIN
BDRV.DBO.HEANDCOUT_BDRV B
ON A.CPF = B.CPF AND A.REF = B.REF 

---- TRATA TABELA FPW

IF OBJECT_ID ('tempdb.dbo.#TBL_FPW') is not null 
DROP TABLE #TBL_FPW

SELECT 
A.REF AS REEF,
A.ID_NUM AS MATRICULA,
B.CPF,
B.NOVA_DIRETORIA,
A.UF,
B.CC,
B.PRODUTO,
B.CARGO_AGRUPADO,
'N/A' AS VALOR_FINAL,
B.MACRO_PRODUTO,
A.SALDO,
A.DESC_EVENTO,
A.SIT_AGRUPADA
INTO #TBL_FPW
FROM BDRV.DBO.RESUMO_FOLHA A
INNER JOIN
BDRV.DBO.HEANDCOUT_BDRV B
ON A.ID_NUM = B.MATRICULA AND A.REF = B.REEF 

--- TBL FOPAG PRIORIDADE

IF OBJECT_ID ('tempdb.dbo.#TBL_FOPAG_PRIORIDADE') is not null 
DROP TABLE #TBL_FOPAG_PRIORIDADE

SELECT A.*,
B.SALDO,
B.DESC_EVENTO,
B.SIT_AGRUPADA
INTO #TBL_FOPAG_PRIORIDADE
FROM #TBL_FOPAG A
LEFT JOIN
BDRV.DBO.RESUMO_FOLHA B
ON A.MATRICULA = B.ID_NUM AND A.REEF = B.REF

INSERT INTO #TBL_FOPAG_PRIORIDADE 
SELECT
A.*
FROM #TBL_FPW A
WHERE NOT EXISTS (SELECT 1 FROM #TBL_FOPAG_PRIORIDADE B WHERE A.MATRICULA = B.MATRICULA AND A.REEF = B.REEF)

---- TABELA MES

IF OBJECT_ID ('tempdb.dbo.#TBL_MES_NN') is not null 
DROP TABLE #TBL_MES_NN

SELECT 
REEF,
MATRICULA,
CPF,
NOVA_DIRETORIA,
UF,
CC,
PRODUTO,
CARGO_AGRUPADO,
VALOR_FINAL,
MACRO_PRODUTO,
SALDO,
DESC_EVENTO,
SIT_AGRUPADA,
RIGHT (REEF,2) AS MEX
INTO #TBL_MES_NN
FROM #TBL_FOPAG_PRIORIDADE


-- TABELA FINAL

IF OBJECT_ID ('BDRV.DBO.RESUMO_DASHBOARD_SEREDE_CONECTA') is not null 
DROP TABLE BDRV.DBO.RESUMO_DASHBOARD_SEREDE_CONECTA

SELECT
A.*,
B.MEES AS MES,
'1' AS ELEGÍVEIS,
CASE WHEN VALOR_FINAL <= '0' THEN 0 ELSE 1 END AS GANHANDO,
LEFT (REEF,4) AS ANO
INTO BDRV.DBO.RESUMO_DASHBOARD_SEREDE_CONECTA
FROM  #TBL_MES_NN A
LEFT JOIN
BDRV.DBO.TBL_MES B
ON A.MEX = B.MES

SELECT * FROM  BDRV.DBO.RESUMO_DASHBOARD_SEREDE_CONECTA
WHERE REEF >= '202201'



