
IF OBJECT_ID ('BDMIS.DBO.PERFORMANCE_RV_RJ') is not null 
DROP TABLE BDMIS.DBO.PERFORMANCE_RV_RJ

-- AGENDAMENTO POR SLOT

IF OBJECT_ID ('tempdb.dbo.#A') is not null 
DROP TABLE #A

SELECT 
SETOR_TEC,
SUM(NUM) AS NUM_AG,
SUM(DEN) AS DEN_AG
INTO #A
FROM BDMIS.dbo.ANALITICO_FERRAMENTA_AGENDAMENTO_MATRIZ WITH (NOLOCK)
WHERE 
MES = 'MARÇO' AND
REFF = '2022' AND
EXPURGO = 'S' AND
PRODUTO IN ('FIXO','VELOX','DTH','VDSL')AND
(matricula_tecnico <> 'OI395240' or matricula_tecnico is null)AND
CAST(REFERENCIA AS DATE)<CAST(GETDATE() AS DATE)
GROUP BY
SETOR_TEC

--EFICÁCIA

IF OBJECT_ID ('tempdb.dbo.#B') is not null 
DROP TABLE #B

SELECT 
SETOR,
SUM(NUM) AS NUM_EFICÁCIA,
SUM(DEN) AS DEN_EFICÁCIA,
'EFICACIA' AS INDICADOR
INTO #B
FROM MIS.DBO.DASHBOARD_FACA_E_RELATORIO WITH (NOLOCK)
where MACROATIVIDADE in ('INST','MUD') AND
PRODUTO IN  ('FIXO' , 'ADSL', 'VDSL')AND
REF = 'MAR/2022' 
GROUP BY
SETOR

-- BACKLOG_48H

IF OBJECT_ID ('tempdb.dbo.#C') is not null 
DROP TABLE #C
 
SELECT SETOR,
SUM (CASE WHEN HORAS > 48 THEN (T) ELSE 0 END) AS NUM_BACK,
SUM (T) AS DEN_BACK
INTO #C
FROM MIS.dbo.HISTORICO_BACKLOG_FACA_B_2 WITH (NOLOCK)
WHERE 
CAST (REF AS DATE) BETWEEN '2022-03-01' AND '2022-03-31'
GROUP BY
SETOR

--SEM PROD. 10H/16H

IF OBJECT_ID ('tempdb.dbo.#D') is not null 
DROP TABLE #D

SELECT SETOR,
SUM (PRES)AS PRES,
SUM (ANTES_10_TOTAL) AS ANTES_10H,
SUM (DEPOIS_16_TOTAL) AS DEPOIS_16H
INTO #D
FROM BDMIS.dbo.PRODUTIVIDADE_TECNICO_ANALITICO_2  WITH (NOLOCK)
WHERE 
FECH_REAL = '_MAR/22' AND
SEGMENTO_NEW IN ('DTH','MULTISKILL','TRIPLE PLAY','VELOX')
GROUP BY
SETOR

-- ESTEIRA
IF OBJECT_ID ('tempdb.dbo.#E') is not null 
DROP TABLE #E

SELECT 
DIR,
UF,
DIST_TEAM AS SETOR,
SUM (CASE WHEN FLAG IN ('OK' , 'CANC' , 'IMPROD') THEN (T) ELSE 0 END) AS NUM,
SUM (T) AS DEN,
'N/A' AS MATRICULATECNICO,
'Esteira' AS INDICADOR
INTO #E
FROM MIS.DBO.ESTEIRA_FACA_B_2
WHERE	 SERVICO IN ('VLX','VOZ','DTH')  AND
MES = 'MAR/2022'
GROUP BY
DIR,
UF,
DIST_TEAM

-- GERENCIA

IF OBJECT_ID ('tempdb.dbo.#FINALIZANDO') is not null 
DROP TABLE #FINALIZANDO

SELECT
A.SETOR_TEC,
SUM(A.NUM_AG) AS NUM_AG,
SUM(A.DEN_AG) AS DEN_AG,
SUM(B.NUM_EFICÁCIA) AS NUM_EFICACIA,
SUM(B.DEN_EFICÁCIA) AS DEN_EFICACIA,
SUM(C.NUM_BACK) AS NUM_BACK,
SUM(C.DEN_BACK) AS DEN_BACK,
SUM(D.PRES) AS PRES,
SUM(D.ANTES_10H) AS ANTES_10H,
SUM(D.DEPOIS_16H) AS DEPOIS_16H,
SUM(E.NUM) AS NUM_ESTEIRA,
SUM(E.DEN) AS DEN_ESTEIRA
INTO #FINALIZANDO
FROM #A A
LEFT JOIN
#B B
ON A.SETOR_TEC = B.SETOR
LEFT JOIN
#C C
ON A.SETOR_TEC = C.SETOR
LEFT JOIN
#D D
ON A.SETOR_TEC = D.SETOR
LEFT JOIN
#E E
ON A.SETOR_TEC = E.SETOR

GROUP BY
A.SETOR_TEC


--INCLUI_GERÊNCIA
IF OBJECT_ID ('tempdb.dbo.#FINAL_CL') is not null 
DROP TABLE #FINAL_CL

SELECT 
A.GER,
SUM(B.NUM_AG) AS NUM_AG,
SUM(B.DEN_AG) AS DEN_AG,
SUM(B.NUM_EFICACIA) AS NUM_EFICACIA,
SUM(B.DEN_EFICACIA) AS DEN_EFICACIA,
SUM(B.NUM_BACK) AS NUM_BACK,
SUM(B.DEN_BACK) AS DEN_BACK,
SUM(B.PRES) AS PRES,
SUM(B.ANTES_10H) AS ANTES_10H,
SUM(B.DEPOIS_16H) AS DEPOIS_16H,
SUM(B.NUM_ESTEIRA) AS NUM_ESTEIRA,
SUM(B.DEN_ESTEIRA) AS DEN_ESTEIRA
INTO #FINAL_CL
FROM #FINALIZANDO B
LEFT JOIN BDMIS.dbo.SETORES_GRA_SEREDE_CONECTA_MATRIZ A
ON A.DIST_TEAM = B.SETOR_TEC
GROUP BY
A.GER

SELECT * FROM #FINAL_CL
