
----- INCLUI NOME DO GR----------------
IF  OBJECT_ID('tempdb..#INDICADORES_MANUTEN플O') IS NOT NULL
DROP TABLE #INDICADORES_MANUTEN플O

SELECT A.DIRE플O,
A.ID_GR,
A.GR,
B.REF,
B.TIPO_EVENTO,
B.ITEM,
NUM, 
DEN
INTO #INDICADORES_MANUTEN플O
FROM BDRV.DBO.FT_MANUTENCAO A
INNER JOIN
[121].BDDO.dbo.FACA_PV_DASHBOARD B
ON A.GRA = B.GRA

-----------TRATA A BASE DOS INDICADORES------------
SELECT 
DIRE플O,
ID_GR,
GR,
SUM(CASE WHEN ITEM = 'PRAZO_EVENTO' THEN NUM END) AS NUM_PRAZO,
SUM(CASE WHEN ITEM = 'PRAZO_EVENTO' THEN DEN END) AS DEN_PRAZO,
SUM(CASE WHEN ITEM = 'TMR' THEN NUM END) AS NUM_TMR,
SUM(CASE WHEN ITEM = 'TMR' THEN DEN END) AS DEN_TMR,
SUM(CASE WHEN ITEM = 'REPETIDA' THEN NUM END) AS NUM_REP,
SUM(CASE WHEN ITEM = 'REPETIDA' THEN DEN END) AS DEN_REP
FROM #INDICADORES_MANUTEN플O
WHERE REF = 'JUN/2021' AND
TIPO_EVENTO = 'PREV'
GROUP BY
DIRE플O,
ID_GR,
GR

-----------TRATA A BASE DOS INDICADORES DIRETORIA------------
SELECT
DIRETORIA,
SUM(CASE WHEN ITEM = 'PRAZO_EVENTO' THEN NUM END) AS NUM_PRAZO,
SUM(CASE WHEN ITEM = 'PRAZO_EVENTO' THEN DEN END) AS DEN_PRAZO,
SUM(CASE WHEN ITEM = 'TMR' THEN NUM END) AS NUM_TMR,
SUM(CASE WHEN ITEM = 'TMR' THEN DEN END) AS DEN_TMR,
SUM(CASE WHEN ITEM = 'REPETIDA' THEN NUM END) AS NUM_REP,
SUM(CASE WHEN ITEM = 'REPETIDA' THEN DEN END) AS DEN_REP,
SUM(CASE WHEN ITEM = 'TEMPO NO POSTO' THEN NUM END) AS NUM_TNP,
SUM(CASE WHEN ITEM = 'TEMPO NO POSTO' THEN DEN END) AS DEN_TNP
FROM [121].BDDO.dbo.FACA_PV_DASHBOARD with (nolock)
WHERE REF = 'JUN/2021' AND
TIPO_EVENTO = 'PREV'
GROUP BY
DIRETORIA

