
---BACKLOG_48H

IF OBJECT_ID ('tempdb.dbo.#B') is not null 
DROP TABLE #B

SELECT 
DIR,
UF,
SETOR,
SUM (CASE WHEN HORAS > 48 THEN (T) ELSE 0 END) AS NUM,
SUM (T) AS DEN,
'N/A' AS MATRICULATECNICO,
'Backlog >48h' AS INDICADOR
INTO #B
FROM MIS.dbo.HISTORICO_BACKLOG_FACA_B_2 WITH (NOLOCK)
WHERE DIR <> 'NULL'  AND
SERVICO = 'FTTH' AND
CAST (REF AS DATE) BETWEEN '2022-02-01' AND '2022-02-28'

GROUP BY
DIR,
UF,
SETOR

-- EFICACIA 

IF OBJECT_ID ('tempdb.dbo.#E') is not null 
DROP TABLE #E

SELECT 
DIR,
UF,
SETOR,
NUM,
DEN,
MATRICULATECNICO,
INDICADOR
INTO #E
FROM MIS.DBO.CONSOLIDA_INDICADORES_FTTH WITH (NOLOCK)
WHERE INDICADOR = 'EFICACIA' AND
MES = 'fev/2022' AND
MACROATIVIDADE = 'INST'

-- RETRABALHO

IF OBJECT_ID ('tempdb.dbo.#R') is not null 
DROP TABLE #R

SELECT 
DIR,
UF,
SETOR,
NUM,
DEN,
MATRICULATECNICO,
INDICADOR
INTO #R
FROM MIS.DBO.CONSOLIDA_INDICADORES_FTTH WITH (NOLOCK)
WHERE INDICADOR = 'RETRABALHO' AND
MES = 'fev/2022' 

-- AGENDAMENTO

IF OBJECT_ID ('tempdb.dbo.#A') is not null 
DROP TABLE #A

SELECT 
DIR,
UF,
SETOR,
NUM,
DEN,
MATRICULATECNICO,
INDICADOR
INTO #A
FROM MIS.DBO.CONSOLIDA_INDICADORES_FTTH WITH (NOLOCK)
WHERE INDICADOR = 'AGENDAMENTO' AND
MES = 'fev/2022' 


-- ESTEIRA
IF OBJECT_ID ('tempdb.dbo.#F') is not null 
DROP TABLE #F

SELECT 
DIR,
UF,
DIST_TEAM AS SETOR,
SUM (CASE WHEN FLAG IN ('OK' , 'CANC' , 'IMPROD') THEN (T) ELSE 0 END) AS NUM,
SUM (T) AS DEN,
'N/A' AS MATRICULATECNICO,
'Esteira' AS INDICADOR
INTO #F
FROM MIS.DBO.ESTEIRA_FACA_B_2
WHERE	 SERVICO = 'FTTH'  AND
MES = 'fev/2022'
GROUP BY
DIR,
UF,
DIST_TEAM

-- UNIÃO

IF OBJECT_ID ('BDRV.DBO.TBL_FTTH') is not null 
DROP TABLE BDRV.DBO.TBL_FTTH

SELECT * 
INTO BDRV.DBO.TBL_FTTH
FROM #B
UNION ALL
SELECT * FROM #E
UNION ALL
SELECT * FROM #R
UNION ALL
SELECT * FROM #A
UNION ALL
SELECT * FROM #F

SELECT * FROM 
BDRV.DBO.TBL_FTTH






