
IF OBJECT_ID ('tempdb.dbo.#INDICADORES_SEREDE') is not null 
DROP TABLE #INDICADORES_SEREDE

-- AGENDAMENTO POR SLOT

IF OBJECT_ID ('tempdb.dbo.#AGEN_CUMP') is not null 
DROP TABLE #AGEN_CUMP

SELECT 
AREA,
SUM(NUM) AS NUMERADOR,
SUM(DEN) AS DENOMINADOR,
'AG_CUMPRIDO' AS INDICADOR
INTO #AGEN_CUMP
FROM BDMIS.dbo.ANALITICO_FERRAMENTA_AGENDAMENTO_MATRIZ WITH (NOLOCK)
WHERE 
MES = 'DEZEMBRO' AND
REFF = '2021' AND
EXPURGO = 'S' AND
PRODUTO IN ('FIXO','VELOX','DTH','VDSL')AND
(matricula_tecnico <> 'OI395240' or matricula_tecnico is null)AND
CAST(REFERENCIA AS DATE)<CAST(GETDATE() AS DATE)
GROUP BY
AREA

-- RETRABALHO

IF OBJECT_ID ('tempdb.dbo.#B') is not null 
DROP TABLE #B

Select
AREA,
SUM(NUM) AS NUMERADOR_RETRABALHO ,
SUM(DEN) AS DENOMINADOR_RETRABALHO ,
'RETRABALHO' AS INDICADOR
INTO #B
FROM MIS.FACA.FACA_RETRABALHO_DASHBOARD_2 WITH (NOLOCK)
WHERE REF = 'DEZ/2021'
GROUP BY 
AREA

--EFICÁCIA

IF OBJECT_ID ('tempdb.dbo.#D') is not null 
DROP TABLE #D

SELECT 
AREA,
SUM(NUM) AS NUMERADOR_EFICÁCIA,
SUM(DEN) AS DENOMINADOR_EFICÁCIA,
'EFICACIA' AS INDICADOR
INTO #D
FROM MIS.DBO.DASHBOARD_FACA_E_RELATORIO WITH (NOLOCK)
where MACROATIVIDADE in ('INST','MUD') AND
PRODUTO IN  ('FIXO' , 'ADSL', 'VDSL')AND
REF = 'DEZ/2021'
GROUP BY
AREA

-- UNIÃO DAS BASES

IF OBJECT_ID ('tempdb.dbo.#FINAL') is not null 
DROP TABLE #FINAL

SELECT * 
INTO #FINAL
FROM #AGEN_CUMP
UNION ALL
SELECT * FROM #B
UNION ALL
SELECT * FROM #D


IF OBJECT_ID ('tempdb.dbo.#FINALX') is not null 
DROP TABLE #FINALX
SELECT
AREA, 
SUM(NUMERADOR) AS NUM, 
SUM(DENOMINADOR) AS DEN, 
INDICADOR,
CASE WHEN SUM(A.DENOMINADOR) = 0 then 0 else 
round(SUM(A.NUMERADOR)/SUM(A.DENOMINADOR),2) end AS PERC
INTO #FINALX
FROM #FINAL A
GROUP BY
AREA,
INDICADOR 

SELECT AREA, 
SUM(NUM_EFICACA) NUM_EFICACIA, 
SUM(DEN_EFICACA) DEN_EFICACIA,
SUM(NUM_RETRABALHO) NUM_RETRABALHO,
SUM(DEN_RETRABALHO) DEN_RETRABALHO,
SUM(NUM_AG) NUM_AG,
SUM(DEN_AG) DEN_AG
INTO #INDICADORES_SEREDE
FROM(
SELECT 
AREA AS AREA,
CASE WHEN INDICADOR='EFICACIA' THEN ROUND ((NUM),2) END AS NUM_EFICACA,
CASE WHEN INDICADOR='EFICACIA' THEN ROUND ((DEN),2) END AS DEN_EFICACA,
CASE WHEN INDICADOR='RETRABALHO' THEN ROUND((NUM),2) END AS NUM_RETRABALHO,
CASE WHEN INDICADOR='RETRABALHO' THEN ROUND((DEN),2) END AS DEN_RETRABALHO,
CASE WHEN INDICADOR='AG_CUMPRIDO' THEN ROUND((NUM),2) END AS NUM_AG,
CASE WHEN INDICADOR='AG_CUMPRIDO' THEN ROUND((DEN),2) END AS DEN_AG
FROM #FINALX) A
GROUP BY AREA


------------------ CRIA TABELA DE PERFORMANCE --------------------

IF OBJECT_ID ('BDRV.DBO.PERFORMANCE_RV_SEREDE') is not null 
DROP TABLE BDRV.DBO.PERFORMANCE_RV_SEREDE

SELECT A.UF,
A.id_serede,
A.NOME_GA,
A.DS_CARGO,
A.DS_STATUS,
SUM (B.NUM_EFICACIA) AS NUM_EFICACIA,
SUM (B.DEN_EFICACIA) AS DEN_EFICACIA,
SUM (B.NUM_RETRABALHO) AS NUM_RETRABALHO,
SUM (B.DEN_RETRABALHO) AS DEN_RETRABALHO,
SUM (B.NUM_AG) AS NUM_AG,
SUM (B.DEN_AG) AS DEN_AG
INTO BDRV.DBO.PERFORMANCE_RV_SEREDE
FROM BDRV.DBO.FT_GESTORES_SEREDE A
INNER JOIN
#INDICADORES_SEREDE B
ON A.AREA = B.AREA
GROUP BY 
A.UF,
A.id_serede,
A.NOME_GA,
A.DS_CARGO,
A.DS_STATUS

SELECT * FROM
BDRV.DBO.PERFORMANCE_RV_SEREDE