
----TABLE UFxGRAxDIR

IF OBJECT_ID ('tempdb.dbo.#TBL_NOVA_RV_LOCAL') is not null 
DROP TABLE #TBL_NOVA_RV_LOCAL

SELECT
A.DIR,
A.UF,
B.SETOR,
B.Mes,
B.ValorBase,
B.ValorMultiplicador,
B.ValorCampanha,
B.ValorBonus,
B.Valor,
B.ValorBruto,
B.Realizado,
B.Meta,
B.MetaPrata,
B.MetaOuro,
B.MetaDiamante,
B.Tipo,
B.Indicador,
B.Categoria,
B.Passou,
B.DiasTrabalhados,
B.DiasUteis,
B.CoeficienteDiasTrabalhados,
B.DataProcessamento,
B.Matricula,
B.Modelo
INTO #TBL_NOVA_RV_LOCAL
FROM BDMIS.DBO.SETORES_GRA_SEREDE_CONECTA_MATRIZ A WITH (NOLOCK)
INNER JOIN
BDRV.DBO.ANALITICO_NOVA_RV B
ON A.DIST_TEAM = B.SETOR

-- INFORMAÇÕES COLABORADOR

IF OBJECT_ID ('tempdb.dbo.#TBL_NOVA_RV_COLAB') is not null 
DROP TABLE #TBL_NOVA_RV_COLAB

SELECT 
A.*,
B.NU_CPF AS CPF,
B.NM_COLABORADOR AS NOME,
B.DS_CARGO AS CARGO,
B.DS_STATUS AS SITUACAO,
B.COD_CENTRO_CUSTO AS CC
INTO #TBL_NOVA_RV_COLAB
FROM #TBL_NOVA_RV_LOCAL A
INNER JOIN
PCP.DBO.HIERARQUIA_GH B WITH (NOLOCK)
ON A.Matricula = B.id_serede

-- INFORMAÇÕES PRODUTO x MODELO

IF OBJECT_ID ('tempdb.dbo.#TBL_NOVA_RV_PROD') is not null 
DROP TABLE #TBL_NOVA_RV_PROD

SELECT
A.*,
B.MACROMODELO
INTO #TBL_NOVA_RV_PROD
FROM #TBL_NOVA_RV_COLAB A
INNER JOIN
BDRV.DBO.TBL_MODELO_NOVARV B
ON A.MODELO = B.MODELO
INNER JOIN
BDRV.DBO.TBL_PRODUTO_NOVARV C
ON A.MODELO = C.PRODUTO


-- TABELA FINAL

IF OBJECT_ID ('tempdb.dbo.#TBL_NOVA_RV_FINAL') is not null 
DROP TABLE #TBL_NOVA_RV_FINAL

SELECT *,
'1' AS ELEGÍVEIS,
CASE WHEN  VALOR <= '0' THEN 0 ELSE 1 END AS GANHANDO
INTO #TBL_NOVA_RV_FINAL
FROM #TBL_NOVA_RV_PROD

SELECT * FROM #TBL_NOVA_RV_FINAL
