
----- INCLUI MES

IF OBJECT_ID ('tempdb.dbo.#TBL1') is not null 
DROP TABLE #TBL1

SELECT UF,
CPF,
NOME,
CARGO,
VALOR_FINAL,
REEF,
REF,
RIGHT (REEF,2) AS MEX
INTO #TBL1
FROM BDRV.DBO.FOPAG_SEREDE_CONECTA
WHERE REEF >= '202001'

----- INCLUI MES2

IF OBJECT_ID ('tempdb.dbo.#TBL2') is not null 
DROP TABLE #TBL2

SELECT A.*,
B.MEES
INTO #TBL2
FROM #TBL1 A
INNER JOIN
BDRV.DBO.TBL_MES B
ON A.MEX = B.MES

------CRIA TABELA RESUMO RV x HC

IF OBJECT_ID ('tempdb.dbo.#RVxHC') is not null 
DROP TABLE #RVxHC

SELECT 
A.REEF,
B.MATRICULA,
A.CPF,
A.NOME,
B.NOVA_DIRETORIA,
A.UF,
B.CC,
B.PRODUTO,
B.CARGO_AGRUPADO,
A.VALOR_FINAL,
B.EMPRESA,
A.MEES,
B.MACRO_PRODUTO
INTO #RVxHC
FROM #TBL2 A
INNER JOIN
BDRV.DBO.HEANDCOUT_PRODUTIVIDADE B
ON A.CPF = B.CPF AND
A.REF =B.REF 

------CRIA TABELA FINAL

IF OBJECT_ID ('BDRV.DBO.RESUMO_DASHBOARD_SEREDE_CONECTA') is not null 
DROP TABLE BDRV.DBO.RESUMO_DASHBOARD_SEREDE_CONECTA

SELECT A.*,
B.SALDO,
B.DESC_EVENTO,
B.SIT_AGRUPADA,
'1' AS ELEGÍVEIS,
CASE WHEN SALDO IS NULL THEN 0 ELSE 1 END AS GANHANDO,
LEFT (REEF,4) AS ANO
INTO BDRV.DBO.RESUMO_DASHBOARD_SEREDE_CONECTA
FROM #RVxHC A
LEFT JOIN
BDRV.DBO.RESUMO_FOLHA B
ON A.MATRICULA = B.ID_NUM AND
A.REEF = B.REF

SELECT * FROM
BDRV.DBO.RESUMO_DASHBOARD_SEREDE_CONECTA


--------- ORÇAMENTO RECEITA-----------

IF OBJECT_ID ('tempdb.dbo.#TBLL1') is not null 
DROP TABLE #TBLL1

SELECT 
TIPO,
UF,
DIRETORIA,
PRODUTO,
CC,
ORCADO,
REALIZADO,
REF,
MACRO_PRODUTO,
LEFT (REF,4) AS ANO,
RIGHT (REF,2) AS MES
INTO #TBLL1
FROM
BDRV.DBO.ORCAMENTO_RECEITA_REMUNERACAO


---ORÇAMENTO

IF OBJECT_ID ('BDRV.DBO.ORCAMENTO') is not null 
DROP TABLE BDRV.DBO.ORCAMENTO

SELECT A.*,
B.MEES
INTO BDRV.DBO.ORCAMENTO
FROM #TBLL1 A
INNER JOIN
BDRV.DBO.TBL_MES B
ON A.MES = B.MES

SELECT * FROM
BDRV.DBO.ORCAMENTO
