
IF  OBJECT_ID('tempdb..#PRODUTIVIDADE') IS NOT NULL
DROP TABLE #PRODUTIVIDADE

SELECT 
A.REF,
C.DIRETORIA, 
C.UF,
C.PRODUTO,
B.DESC_EVENTO,
A.ID_NUM,
A.NOME,
A.SITUACAO,
D.CARGO_AGRUPADO,
C.MACRO_PRODUTO,
CASE WHEN B.[D/C] = 'Crédito' then -[VALOR] ELSE [VALOR] END AS SALDO 
INTO #PRODUTIVIDADE
 FROM 
BDRH.FPW.CONTABILFOLHA A WITH (NOLOCK)
LEFT JOIN
BDRH.CUSTO.Tbl_Evento_Conta B WITH (NOLOCK)
ON
A.COD_EVENTO=B.EVENTO
LEFT JOIN
BDRH.CUSTO.TBL_CENTRO_CUSTO C WITH (NOLOCK)
ON
A.CENTRO_CUSTO_NUM=C.[CENTRO_CUSTO_NUM]
LEFT JOIN
BDRH.CUSTO.TBL_CARGO_AGRUPADO D WITH (NOLOCK)
ON
A.COD_CARGO=D.COD_CARGO
WHERE REF >= '202101'
AND CONTA_SEREDE = '31102004'

SELECT 
REF,
DIRETORIA, 
UF,
PRODUTO,
DESC_EVENTO,
ID_NUM,
NOME,
SITUACAO,
CARGO_AGRUPADO,
MACRO_PRODUTO,
SUM (SALDO) AS TOTAL
FROM 
#PRODUTIVIDADE
GROUP BY
REF,
DIRETORIA, 
UF,
PRODUTO,
DESC_EVENTO,
ID_NUM,
NOME,
SITUACAO,
CARGO_AGRUPADO,
MACRO_PRODUTO


