
--BASE_COLABORADOR

IF OBJECT_ID ('tempdb.dbo.#BASE_01') is not null 
DROP TABLE #BASE_01

SELECT 
NU_CPF AS CPF_COLABORADOR,
DT_ADMISSAO AS DATA_ADMISSAO,
DS_FILIAL AS REGIONAL_TÉCNICO,
ID_SEREDE AS ID_COLABORADOR,
NM_COLABORADOR,
cod_centro_custo AS CENTRO_DE_CUSTO,
ds_centro_custo AS DESCRIÇÃO_CC,
ds_cargo AS CARGO,
ds_status AS STATUS,
ID_GESTOR_IMEDIATO AS ID_GESTOR,
nm_gestor_imediato AS NOME_GESTOR
INTO #BASE_01
FROM PCP.dbo.hierarquia_gh WITH (NOLOCK)

---BASE GESTOR

IF OBJECT_ID ('tempdb.dbo.#BASE_02') is not null 
DROP TABLE #BASE_02

SELECT
ID_SEREDE,
nu_cpf AS CPF_GESTOR,
DS_FILIAL AS REGIONAL_GESTOR
INTO #BASE_02
FROM PCP.DBO.hierarquia_gh WITH (NOLOCK)
WHERE 
DS_CARGO IN ('DIRETOR ADMINISTRATIVO FINANCEIRO','GER GERAL SERVICO AO CLIENTE','DIR OPERACIONAL','COORDENADOR ADMINISTRATIVO PATRIMONIAL','GERENTE CORPORATIVO FROTA','GERENTE JURIDICO','GERENTE FINANCEIRO','GERENTE LOGISTICA','GER CONTROLADORIA E FINANCAS','COORDENADOR CONTABIL FISCAL','COORDENADOR SEGURANCA CORPORATIVA','GERENTE DE SESMT','GER SEGURANCA CORPORATIVA','GER REG JURIDICO','GER FOLHA DE PAGAMENTO','COORDENADOR FINANCEIRO','DIR GENTE E GESTAO','DIRETOR GERAL DE OPERACOES','DIR GERAL','COORD SUPRIMENTOS','DIRETOR COMPLIANCE','DIR NOVOS NEGOCIOS','GER TI E SOLUCOES','COORD REG SEG PATRIMONIAL','GER LOGISTICA','COORD CAPACITACAO OPERACIONAL','COORDENADOR REMUNERACAO','COORDENADOR RECRUTAMENTO E SELECAO','COORD REG SESMT','COORDENADOR REG DE SEGURANCA PATRIMONIAL','COORD FISCAL','COORDENADOR DE LOGISTICA','COORDENADOR REG FACILITIES','GER GERAL REDE DE ACESSO','GER GERAL FIBRA OPTICA','GESTOR DE AREA REDE ACESSO I','GESTOR DE CONTROLE LOCAL I','GESTOR DE AREA DG','COORDENADOR REG RECRUT E CAPACITACAO','GERENTE REG RECURSOS HUMANOS','COORDENADOR CONSULTORIA INTERNA RH','GER GERAL DE OPERACAO SERV CLIENTES','COORD BENEFICIOS','GER GERAL FIBRA OTICA E DADOS','GERENTE DE CONTROLE LOCAL','DIRETOR DE OPERACOES','COORDENADOR PLANEJ E ORCAMENTO RH','COORD GESTAO E METODOS','GESTOR DE AREA REDE DE ACESSO II','GERENTE DE OPERACOES','GER RELACOES SINDICAIS','GER AUDITORIA INTERNA','GER DESENV ORGANIZACIONAL','COORD CONTRATOS','COORD SAUDE OCUPACIONAL','GER OPERACOES REDE DE ACESSO','COORDENADOR REG FROTA','COORDENADOR LOGISTICA','ESPECIALISTA RECURSOS HUMANOS','GER CONTROLE LOCAL','GER REG RECURSOS HUMANOS','GER SUPORTE OPERACOES','COORDENADOR DESEMPENHO FINANCEIRO','COORDENADOR SALA TECNICA','GERENTE SALA TECNICA','GER SALA TECNICA','COORDENADOR SISTEMAS E SOLUCOES','GERENTE DE OPERACOES FIBRA OTICA','GER REMUNERACAO E PLANEJ RH','COORDENADOR REG SESMT','COORDENADOR AUDITORIAS DE CAMPO','GERENTE SUPORTE OPERACOES','COORDENADOR BACKOFFICE','COORDENADOR REG QUALIDADE','GER OPERACOES FIBRA OTICA','GER OPERACOES SERVICO CLIENTE','GESTOR DE AREA SERVICO AO CLIENTE I','GER FIBRA OTICA E DADOS','COORD SALA TECNICA','COORDENADOR DE TI','GERENTE DE OPERACOES DADOS','COORD REG QUALIDADE','COORDENADOR REG JURIDICO','GERENTE SUPRIMENTOS E PATRIMONIO','GESTOR DE AREA REDE DE ACESSO I','GESTOR DE AREA FIBRA OTICA I','COORD REG FROTA','COORD ADM PESSOAL','GER GERAL OPERACOES','GESTOR DE CONTROLE LOCAL II','GER COMUNCACAO INSTITUCIONAL','GER CONTRATOS E PRECIFICACAO','INSTRUTOR AUDITOR','GERENTE REG PLANEJ E CONTROLE DE PRODUCAO','COORD REG PCP','COORDENADOR PROJETOS','COORD LOGISTICA','SUPV CRM','ESPECIALISTA ADM DE PESSOAL','COORDENADOR ESCRITORIO DE PROJETOS','COORDENADOR REMUNERACAO VARIAVEL','COORD FOLHA DE PAGAMENTO','GER OPERACOES DADOS','GESTOR DE AREA DADOS I','GESTOR DE AREA SERV CLIENTE I','COORD FROTA','GER GERAL LABORATORIO TECNICO','COORDENADOR REG ADM DE PESSOAL','COORD REG LOGISTICA','COORD PLANEJAMENTO','ESPEC PLANEJAMENTO','GERENTE COMPLIANCE E CONTROLES INTERNOS','COORD PROJETOS','GER OPERACOES','SUPV ALMOXARIFADO','GER OPERACAO RECURSOS HUMANOS','COORD REG VENDAS','SUPV LOGISTICA','COORDENADOR DE FTTH','ESPEC INFORMACOES GERENCIAIS','GER PCP','COORD PCP','GER GERAL DE CONTROLE LOCAL','COORDENADOR RECURSOS HUMANOS','SUPERVISOR SUPORTE VENDAS','COORDENADOR LABORATORIO TECNICO','COORDENADOR REPORT','GER VENDAS','GERENTE VENDAS','GER GERAL FIBRA OTICA','GER GESTAO CORPORATIVA','COORD QUALIDADE','SUPV FROTA','ANALISTA QUALIDADE SR','GER REG PCP','GER REG QUALIDADE','COORD PREV E APURACAO FRAUDE','GERENTE REG QUALIDADE','GESTOR DE AREA TRAINEE','COORD VENDAS','COORDENADOR VENDAS','COORD PROCEDIMENTOS PRODUTIVOS','GERENTE AUDITORIAS DE CAMPO')


---BASE FINAL

IF OBJECT_ID ('tempdb.dbo.#BASE_CAGEN') is not null 
DROP TABLE #BASE_CAGEN

SELECT A.CPF_COLABORADOR, 
B.CPF_GESTOR,
A.DATA_ADMISSAO,
A.REGIONAL_TÉCNICO,
A.ID_COLABORADOR,
A.NM_COLABORADOR,
A.CENTRO_DE_CUSTO,
A.DESCRIÇÃO_CC,
A.CARGO,
B.REGIONAL_GESTOR,
A.ID_GESTOR,
A.NOME_GESTOR,
A.STATUS
INTO #BASE_CAGEN
FROM #BASE_01 A
INNER JOIN
#BASE_02 B
ON A.ID_GESTOR = B.ID_SEREDE

IF OBJECT_ID ('tempdb.dbo.#BASE_CAGEN_FINAL') is not null 
DROP TABLE #BASE_CAGEN_FINAL

SELECT A.*,
B.MATRICULA
INTO #BASE_CAGEN_FINAL
FROM #BASE_CAGEN A
INNER JOIN
[10.22.75.121,1452].BDRH.INDICADORES.FOPAG_SEREDE B WITH (NOLOCK)
ON A.CPF_COLABORADOR = B.CPF
WHERE 
REF = '202104'

SELECT * FROM
#BASE_CAGEN_FINAL